### ISSUE TITLE
Split ligature vs. marked zero

### ISSUE THREAD

**Issue by egmontkob** [kent-karlsson/control#11]
As already pointed out in https://github.com/kent-karlsson/control/issues/1#issuecomment-1383774084, the proposed CSI 57m combines two features that I believe should be absolutely independent from each other.

Why would ligatures have anything to do with the look of the '0' digit? Why is it not two separate, independent numbers controlling their behavior?

---

The suggested values are unclear to me.

> CSI 57:1[:v]m Allow modern ligatures [...] do not mark zero [...] Variants, v: :0 only affect “0”

How can something that says to "do not mark zero" later possibly either "affect 0" or not? Does this override the previous sentence?

Similarly:

> CSI 57:2[:v]m No ligatures but mark zero [...] Variants, v: [...] :1 only affect ligaturing

If you say "no ligatures", how can a followup parameter potentially specify to "only affect ligaturing"?

It is utterly unclear to me how many underlying properties are there, how many possible values each of them has, and how each combination of parameters exactly affects each of them.

---

> CSI 57[:0]m Reset to default w.r.t. ligatures and marked zero.

What is the default that it resets to?

---

What does "optional (discretionary) ligatures" exactly mean; given that, even for ligatures that don't fall into this category, this proposal aims to specify how to turn them on or off, making them also _optional_?

**Comment by egmontkob** [comment]
I'm _trying_ to understand the proposed values.

There is a boolean (the look of the "zero"). The value is upside down: _true_ (_set_) value means to _not_ mark them, the _false_ (_unset_) value means to mark them.

And there's a tri-state (ligatures: nothing, "modern" only, or "modern" + "optional"), which I should probably imagine as two booleans (with intuitive values, _set_ for enabled): one for "modern" ligatures and one for "optional" ligatures, whereas the second one can only be _set_ if the first one is also _set_ (i.e. the combination 01 is illegal).

CSI 57:1 _sets_ some of the bits. Either the "zero" only, or the "modern ligature" only, or both of these, or both of these and even the "optional ligatures". Well, there are 2x3 options (since there's a bi-state and a tri-state underlying value), and not altering either of them is pointless. But that still means that one option is missing. It's not possible to enable the two kinds of ligatures, while leaving the "zero" at its previous (possibly unset) state. It is possible to achieve this state via a workaround: an 57:1:3 (set all three bits) followed by an 57:2:0 (unset the "zero" bit). That is, if you know that the previous state was unset, and not some value that's unknown to you and wish to leave that unchanged. Huh.

CSI 57:2 _unsets_ some of the bits. Either the "zero" only, or both kinds of ligatures (whereas the same sub-number for 57:1 meant the normal ligatures only, pretty confusing), or ":2 affect both" (somewhat unclear what the word "both" means to, probably to both of the previous sub-numbers, i.e. to all three bits) (again, the meaning of the sub-number 2 is different from 57:1:2, pretty confusing), or the "optional ligatures". Again, one option is missing, namely to turn off the "zeros" and the "optional ligatures", while keeping the "normal ligatures". It's possible to achieve this by emitting an 57:2:0 and an 57:2:3.

That is, _if_ I'm understanding this correctly.

(Do I understand it incorrectly, and the correct way to interpret it makes way more sense than this??)

**Comment by kent-karlsson** [comment]
Working draft summary on this point:

CSI 57[:0]m Reset to default w.r.t. ligatures.
CSI 57:1m Only required ligatures.
CSI 57:2m In addition to required ligatures, use also modern ligatures (according to the font).
CSI 57:vm, v = 3 or greater. Reserved for future use.

CSI 67[:0]m Uppercase fixed width digits (default).
CSI 67:1m Lowercase fixed width digits.
CSI 67:2m Uppercase proportional width digits.
CSI 67:3m Lowercase proportional width digits.
CSI 67:99m Uppercase fixed width digits, where the (ASCII) 0 has a middle dot or an internal diagonal stroke.
