### ISSUE TITLE
Don't waste 3 numbers for proportional width

### ISSUE THREAD

**Issue by egmontkob** [kent-karlsson/control#12]
Given the new practice of the first parameter controlling the property and the second controlling its value,

-- e.g. a single CSI 113 for vertical halving, a single CSI 56 for super-/subscripts, a single CSI 57 for ligatures, a single CSI 74 line spacing, etc. --

the choice to pick to CSI 66 and 67 for small caps is at least questionable (but at least it follows the old practice),

whereas to pick _three_ brand new numbers, CSI 69, 70 and 71 for proportional width, instead of just one (or perhaps two) with a subparameter, is absolultely unjustified.

**Comment by kent-karlsson** [comment]
Working draft summary re. small caps:

CSI 66[:0]m Normal uppercase and lowercase rendering (default). Implies CSI 67[:0]m.
CSI 66:1m Uppercase letters, 0 to 9, and & rendered as small caps.
CSI 66:2m Uppercase letters, 0 to 9, and & rendered as petit caps.
CSI 66:666m Lowercase letters rendered as the petit caps of their uppercase. Language dependent.
CSI 66:999m Lowercase letters rendered as the small caps of their uppercase. Language dependent.
