### ISSUE TITLE
Blinking frequency

### ISSUE THREAD

**Issue by egmontkob** [kent-karlsson/control#14]
ECMA-48 says "less then[sic] 150 per minute" and "150 per minute or more".

You change these to "approx. 1,5 Hz to 2 Hz" and "approx. 2,5 Hz to 3 Hz", respectively.

I believe that in most graphical terminal emulators the "on" and the "off" states of slow blinking each take up somewhere between 0.5 and 1 s, making the entire cycle between 1 and 2 s, thus the blinking frequency somewhere between 0.5 and 1 Hz.

(GNOME's default for the blinking cursor is 1200 ms cycle, i.e. 0.833 Hz, and VTE follows the cursor's blinking speed for blinking text, too. In KDE's Konsole the text blinks differently than the cursor, the text seems to go for me in sync with the clock, i.e. 1 Hz.)

Thus changing the intervals, compared to old ECMA, is unjustified.

---

Two nitpicks:

English uses decimal point, not decimal comma.

Typo: "rabid" in your document.

**Comment by kent-karlsson** [comment]
Revised; basically back to what ECMA-48 says, no extra limits.
(In my draft, not uploaded yet.)

**Comment by kent-karlsson** [comment]
"Two nitpicks:
English uses decimal point, not decimal comma."

I follow https://www.iso.org/ISO-house-style.html here: 
"The decimal sign is a comma and is placed on the line." (except for numbers before imperial unit symbols)

"Typo: "rabid" in your document."

Will fix the typo.
