### ISSUE TITLE
SPD concerns

### ISSUE THREAD

**Issue by egmontkob** [kent-karlsson/control#17]
In ECMA-48 and ECMA TR/53, `SPD 0` and `SPD 3` are horizontally symmetrical counterparts of each other. Whether to apply BiDi treatment is controlled by an orthogonal property (`BDSM`).

In your proposal `SPD 0` and `SPD 3` are no longer symmetrical, the horizontally symmetrical counterpart of `SPD 3` becomes the new `SPD 8` (instead of `SPD 0`). What's the rationale behind this change? Aren't there any compatibility concerns here?

"Visual RTL", i.e. encoding RTL text in LTR direction, i.e. reversing the order of the letters in the underlying data (e.g. for use with an LTR-only viewer working with the ISO 8859-8 character set), has been considered a bad practice for at least three decades. Unicode 1.0, released in 1991, already states that the document should contain the logical order, already includes `LRE` and friends, and already specifies the BiDi algorithm (which was later split into a separate document). And I'd _guess_ it didn't arise out of the blue but rather might have been based on earlier works.

There are a few leftover cases where "visual RTL" might be needed. Terminal emulation is one of them, because certain applications (e.g. text editors), by design, only send the visible part of the text to the terminal emulator, so then the BiDi algorithm can only be run in the text editor, not in the terminal emulator. (In other words, due to legacy architecture, there is an API between two components where one has to transmit the rendered final visual layout rather than the underlying logical data, although has to do it in terms of characters rather than pixels.) Probably terminal emulation is the only such platform that is likely to live on for decades, other ones like teletext are quickly dying out and are extremely unlikely to adopt any new feature you come up with.

For a newly popularized _document format_, "visual RTL" order shouldn't be a thing. (In the unlikely and extremely rare case that someone needs it somewhere, `LRO` is still available.)

Other than for interoperatibility with terminal emulators (and dying platforms like teletext), this mode (your `SPD 0`) should not exist, and should not "demote" the proper BiDi handling feature to a different numeric slot (`SPD 8`). And, again, for terminal emulators, the ECMA way of enabling this "visual order" mode ("explicit" mode as ECMA calls it) is `BDSM`, not `SPD`.

Your document continues by saying

> CSI 99!V (new) Reset to default directions, per preference setting

which implicitly suggests that even without this escape sequence, the default is subject to a "preference setting".

It's obvious that a piece of RTL (or mixed) text either shows up correctly in your `SPD 0` mode _or_ in your `SPD 8` mode, not both. Correct vs. broken behavior must not be subject to a user preference setting.

Please revert to what ECMA says here, it makes more sense than your proposal.

**Comment by kent-karlsson** [comment]
I have split out SPD2 from SPD, letting SPD2 be an _extension_ to SPD, with no proposed change to SPD.

For SPD there is no bidi processing, and only two of the SPD2 variants allow for bidi processing,
one per paragraph direction setting.
