### ISSUE TITLE
Escape sequence choice for hyperlinks

### ISSUE THREAD

**Issue by egmontkob** [kent-karlsson/control#2]
As you know, there's already a somewhat widespread escape sequence for denoting hyperlinks (myself being a co-designer of).

Let's put aside whether the choice for that escape sequence is a good one or not (a long time ago you said that OSC should've been APC, and now you're going with SOS -- really, I know you're not satisfied with OSC, but let's put it aside).

You pick SOS a=url ST displaytext STX.

I have two problems with this.

---

First, I'm not sure that this is the right replacement for the allegedly bad choice of OSC.

SOS and ST are probably fine, ECMA-48 says "SOS is used as the opening delimiter of a control string" and ST we all know is the string terminator. Looks good to me.

STX - not so much. ECMA-48 says "STX is used to indicate the beginning of a text and the end of a heading. The use of STX is defined in ISO 1745."

At https://www.iso.org/standard/6365.html I could buy ISO 1745 for CHF 124. No thanks. Allegedly it's free under the name ECMA-16 containing the identical contents. At https://www.ecma-international.org/publications-and-standards/standards/ecma-16/ it's marked as "withdrawn" with no pointer to a successor document. It can be viewed as scanned (unsearchable) pages. At bullet point 3.1.2 it elaborates on what ECMA-48 said but it's basically the same: it's "used to terminate a Heading", presumably one opened with the SOH (Start of Heading) character.

This doesn't fit the hyperlink use case. There's no header to terminate; and in fact, no text to _start_ either, since the previous characters are also visible text (with some optionally supported additional functionality and visual representation). You wouldn't say "start of text" after a "bold off", would you? This is no different.

Therefore I'd claim that _even if_ OSC was the wrong choice and it should've been APC or SOS (which I'm not saying is the case), the seemingly improper use STX doesn't make your new proposal any better.

---

The second one is a more fundamental problem. Let me start from far away.

Let's suppose you want to achieve a text that looks like:

    normal text - bold text - bold-and-italic text - italic text - normal text

In terminal escape sequences, it's perfectly legal to go like

    text [bold on] text [italic on] text [bold off] text [italic off] text

obviously using the actual escape sequences instead of the ad-hoc placeholders I've shown.

On the other hand, in HTML you can _NOT_ go like this. Tags have to be properly nested. To achieve the above layout, you'd have to go something like

    text [bold on] text [italic on] text [italic off][bold off][italic on] text [italic off] text

This is because the language of the web (HTML) works with a document tree model, whereas terminals follow a state machine model. (One is not strictly better than the other, both worlds have advantages and disadvantages.)

Now, there's one property of hyperlinks that we shouldn't forget about: their visible text can also contain further tags, such as attribute changes, images etc. It's crucial that we don't drop this flexibility, don't introduce the limitation that the entire clickable text would need to have the same visual properties throughout.

Maybe currently hyperlinks feature is a one-of-a-kind, but who knows what comes in the future. Maybe you want to have an attached text to each character cell that is used as a tooltip popup text. (We've heard someone misuse the hyperlink feature for this purpose). Or a footnote text. Or whatever. Presumably you'd still pick the SOS ... ST ... STX framework that, too, right?

And how do you know which STX corresponds to which SOS ... ST? Remember, we do want these properties to be able to overlap. Probably your only chance is to come up with a stack, the STX corresponds to the most recently opened SOS ... ST. And at this moment you're back to the DOM model of HTML, rather than the state machine model of terminals.

[By the way, hyperlinks are special in the sense that closing and re-opening the same is not a no-op, they do have a visual effect (underlining on hover stops there). So it's always whichever other tag that it interleaves with is the one you'll have to close and reopen.]

With the design of OSC 8 hyperlinks, we deliberately (as it's mentioned in its documentation) "translated" the syntax from the DOM-like model of the web to the state machine-like model of terminal emulators, so that it fits well with the rest of what happens in terminals. You revert this change.

You pick a language that you'd like to become more widespread, a language that uses the state model approach. And take one component of it, and change it not to use the state model approach but rather the stack/dom approach. Therefore applications that intend to handle this format would have to support a weird and unreasonable mixture of the two worlds, rather than cleanly just the state machine world. And it would impose an additional requirement for hyperlinks, a requirement that isn't there for other attributes.

If you want to update and popularize a language that uses the state machine model, please stick to the state machine model so that one can use all its advantages without compromises. In the state machine model, the closing tag has to tell which attribute exactly it turns off.

**Comment by kent-karlsson** [comment]
I'll remove any particular hint/suggestion. Note that this "possible use" never has been a part
of this proposal anyway! It is important to note that this was just a "possible use".
