### ISSUE TITLE
CSI 22:v problem

### ISSUE THREAD

**Issue by egmontkob** [kent-karlsson/control#4]
You say

> CSI 22[:v]m [...] Same variants as for bold/lean, but the default is :0.

But it cannot be the same as for "bold/lean" because for bold (CSI 1) and lean (CSI 2) the values mean different things.

You need to be more precise, e.g. say the values are the same as "bold".

My recommendation: Leave out the `:v` possibility all throughout for the values that reset. After all, if one needs any parameter, they should be using the setter number.

**Comment by kent-karlsson** [comment]
I've changed (in my draft, not uploaded yet) to use the font weight numbers as
in OpenType and CSS (1 to 1000 inclusive). One could leave out the [:v] for CSI 22m;
but then again that is not how it is done e.g. for underlining (already) IIUC.
