### ISSUE TITLE
Small caps issue

### ISSUE THREAD

**Issue by egmontkob** [kent-karlsson/control#5]
4.9 says "Small caps style is often the preferred style for abbreviations in uppercase" - I don't see this claim being backed up.

Then it follows with "CSI 66[:v]m Display uppercase letters as small caps. Lowercase letters are not affected." - According to my experience, as well as backed up by the [wiki page](https://en.wikipedia.org/wiki/Small_caps), small caps is not this.

Small caps is a styling where uppercase letters are displayed as-is, but lowercase letters are replaced by their uppercase counterpart glyphs displayed in a smaller size.

**Comment by kent-karlsson** [comment]
It is a common typographic recommendation, to make the "blackness" of the page look more "even".
Perhaps I should have written "acronyms" rather than "abbreviations".
See the first two paragraphs under "Uses" in https://en.wikipedia.org/wiki/Small_caps.

OpenType feature c2sc (Small Capitals from Capitals) (simulate if not available), normal use for uppercase abbreviations/acronyms: CSI 66:1m, CSI 66m.

OpenType feature smcp (Small Capitals [from lowercase]) (map to uppercase and simulate if not available), sometimes used in titles/headings and leading text of first paragraph:  CSI 66:999m.

**Comment by egmontkob** [comment]
According to the said wiki page (two screenshots):

> ![small-caps-1](https://user-images.githubusercontent.com/5750745/215737192-d39a4c3a-d9f4-49a0-8be6-6c5ef9c3b0c7.png)

and

> ![small-caps-2](https://user-images.githubusercontent.com/5750745/215737531-c86758f6-cd8c-441b-b468-e04ec5778fa0.png)

Study the page and its source code. Copy-paste the text from that page into an environment that doesn't support small caps and see how it behaves.

My _guess_, trying to reverse engineer what you wrote, is that you believe that the source text is full uppercase and either only the letters that are supposed to appear bigger, or the complement set, only the letters that are supposed to appear smaller, are marked as "small caps". I might easily be wrong with this guess, of course, but this faulty interpretation could justify what your proposal says.

The source text is mixed case. The entire piece of text is supposed to be marked as "small caps". Lowercase letters of the source will appear as smaller uppercase glyphs, uppercase letters of the source will appear as bigger uppercase glyphs. This is how small caps works.

Stating that

> Lowercase letters are not affected.

will clearly never get you this result, and suggests that you might fundamentally misunderstand small caps.

**Comment by kent-karlsson** [comment]
CSS supports true small caps (c2sc in OpenType) only through the inconvenient 'font-feature-settings: "c2sc"'.
The other "small caps-like" variants have more convenient expressions too. That is a CSS problem which I
cannot fix in this proposal. Please contact the CSS team at W3C. CSS really should support true small caps (c2sc), 
the type of small caps that is the most useful, in a more convenient way (like 'true-small-caps').

I haven't deep analysed Wikipedia on this point, but I think what you are looking for is (most closely)
implemented as the "template" Smallcaps2: https://en.wikipedia.org/wiki/Template:Smallcaps2, though not 
perfectly. However, I'm not going to fix the wikipedia page on small caps. But please feel free to do so.

**Comment by egmontkob** [comment]
I've typed `Hello World` into LibreOffice Writer, highlighted the _entire_ text, then choose right click -> Character -> Character... -> Font Effects -> Case: Small capitals (I googled how to do this, this was the first result). The result is:

![small-caps-3](https://user-images.githubusercontent.com/5750745/216535318-d59a5992-3bda-4ab8-b9f2-a565b29d2eff.png)

This perfectly matches what Wikipedia says, what CSS `font-variant: small-caps` does, what LaTeX's `{\sc ...}` or `\textsc{...}` does, what the first software where I ever encountered this concept did (I believe it was ChiWriter), what I've believed "small caps" to mean ever since, and what I firmly believe the common interpretation of "small caps" is.

Now, if I understand you correctly, "small caps" is actually not one concrete font effect, but a family of such effects with at least (or exactly?) two members. One of them is the one I'm talking about and shown above (I don't know its name, I'll call it "traditional" for now). Another member is "true small caps" which is something different.

I'm pretty certain that the "traditional" version is way more widespread and this is what the vast majority of people think of when hearing "small caps", not the "true" one. Anywhere I've seen so far this is either the only mode offered, or the more easily, more conveniently reachable mode.

---

I'm trying to understand the subparameters in your proposal.

The subparameter of "1" refers to "true small caps" (CSS: c2sc).

The subparameter of "999" seems to refer to what I'd expect to see as "small caps" (the "traditional" one, CSS: smcp) and what I've shown in the screenshots above.

My concerns:

The phrasing is extremely poor here, which led me to misunderstand it. It begins "CSI 66[:v]m" with four lines of text describing the behavior, then comes variant :1 to state that it's like said in the previous 4 lines, and then comes variant :999 which overrides (invalidates, contradicts) several things that those common 4 lines said. That's not how to phrase it. Put in the common section what is indeed common to both modes. Put under variant :1 that is specific to variant :1, such as the underlined sentence "Display uppercase letters as small caps" and the following sentence "Lowercase letters are not affected", since these are indeed specific to variant :1 and do not apply to :999. Do not have sentences that contradict, override earlier ones.

Also, if you believe that underlining that sentence is important then underline its counterpart under :999, too. But I think you're using underlining a summary of the paragraph, so it should be a generic sentence that applies to both sub-modes, such as "Apply small-caps look to the text".

> true small caps (c2sc), the type of small caps that is the most useful

According to whom?

"traditional" (smcp) is way more frequently used than "true" (c2cs), it gets the major focus on the Wiki page, it is the only possibility in some software (e.g. LibreOffice), it is the more easily reachable one at other places (e.g. CSS), this is what I see everywhere on the google "image search" results for "small caps".

Don't go against the crowd. Your subjective preference doesn't matter. smcp has to be the default and take number 1.

c2sc can be number 2 rather than the ridiculous arbitrary choice of 999.

---

CSS at font-variant-caps says:

> small-caps
>     Enables display of small capitals (OpenType feature: smcp). Small-caps glyphs typically use the form of uppercase letters but are reduced to the size of lowercase letters. 

So _this_ is what CSS also calls _the_ "small-caps", "small capitals" feature, the other possible behaviors all have their distinct names.

Also, other values include all-small-caps (c2sc+smcp) and quite a few others (which you could consider including in your spec), but not c2sc on its own (it's only available through the inconvenient "font-feature-settings" as you've shown).

I really don't know the answer, but I'm wondering: Are you absolutely sure that you know it better than the W3C folks that c2sc on its own is waaaay more useful than smcp+c2sc (to the extent that the former is not only available but is outright the default value in your proposal, while the second one isn't even available; whereas in CSS the second one is available directly and the first one is only through some quirks)?

What I see is that (apart from the very bad editing of the paragraph where mode 999 contradicts the common parts) you're going against the wind. Favoring c2sc over smcp, and claiming that Wikipedia should be fixed: I am confident that it's not a rational move but instead you're pushing your personal favorite against real life use and widespread concept about this feature. Favoring c2sc over c2sc+smcp, stating that you know it better that CSS: I cannot judge, but based on seeing how you're going against the wind, let me just say that I have some doubts here too.
