### ISSUE TITLE
Negative image concern

### ISSUE THREAD

**Issue by egmontkob** [kent-karlsson/control#6]
At 4.19.8 you correctly state that CSI 7m is defined in ECMA-48 as "negative image", whereas typically "has [...] been interpreted as switching background and foreground colors" (a.k.a. reverse or inverse video).

However, you say that this is an "erroneous" interpretation, the correct one should be "photo negative".

I don't see this conclusion justified; I find it more likely that the intent was inverse video, and it was a poor choice of wording in the standard. (Yes, documentation, standards etc. can also be buggy, not just implementations.)

The world has clearly settled with "reverse video", which is arguably way more useful than the (IMHO) utterly useless "photo negative". (Mind you, it's unspecified what to do with underline, shadow etc. color that weren't part of ECMA-48.)

I'm not aware of any terminal or any other software/hardware implementing this as photo negative, but let me know if there's any.

Why force the presumably poorly worded but then literally interpreted approach, which is not at all use in today (perhaps never was), rather than fixing (or adjusting) the wording of the standard to the widespread and useful interpretation?

**Comment by kent-karlsson** [comment]
https://en.wikipedia.org/wiki/Reverse_video: "Reverse video (or invert video or inverse video...",
"Video is usually reversed by inverting the brightness values of the pixels of the involved 
region of the display. If there are 256 levels of brightness, encoded as 0 to 255, the 255 
value becomes 0 and vice versa. A value of 1 becomes 254, 2 of 253, and so on: n is swapped 
for r - n, for r levels of brightness."

I.e. "photo negative".

As for usefulness, they are about the same, or, if you like, in the eye of the beholder.
The "photo negative" is somewhat better looking... Both are kind of ugly, I would agree to that.
Note that the "swap" interpretation, by whatever name, has no correspondence anywhere
outside of terminal emulators.

The "background colour" is in general 100% transparent. Probably not what you want for
foreground colour. Look at the colour planes discussion in the beginning of section 4.19.

In effect, I'm saying that the "swap" interpretation is in general not working well, esp. not with
more than two colour layers.

**Comment by egmontkob** [comment]
> https://en.wikipedia.org/wiki/Reverse_video: [...] 
> 
> I.e. "photo negative".

Accompanied with a screenshot where the reverse of green-on-black is black-on-green, not magenta-on-white.

> As for usefulness, they are about the same, or, if you like, in the eye of the beholder.
> The "photo negative" is somewhat better looking... Both are kind of ugly, I would agree to that.

That very screenshot looks nice to me, but would look terrible with "photo negative" interpretation.

**Comment by kent-karlsson** [comment]
You see the effect of: a) 1 bit per pixel, b) green flourecent coating in the CRT, no actual colour
capability. Then "photo negative" has that effect. It was quite common some decades ago, that
terminals (actual "terminals", not emulators) were like that, green or yellow were "popular"
monochrome colours for terminals in those days, using one bit per pixel (on or off).

I can agree that "photo negative" can be ugly on a full colour display (as is common today),
but so is the "swap" interpretation, which I suffer almost every day..., when this is used
for *local* side text selection marking (no control sequences, not so often seen/used from
the remote side with control sequences).

See section 9 of my proposal for a more modern UI approach to marking "selected" text
(via control sequences from the remote side); BUT the *effect* can be used locally as well
(no control sequences) even without adopting section 9 of my proposal.

**Comment by egmontkob** [comment]
> You see the effect of: a) 1 bit per pixel, b) green flourecent coating in the CRT, no actual colour
capability. Then "photo negative" has that effect.

No. It doesn't matter how many colors are available. Even if black and green are the only available colors, it does _not_ make black-on-green the photo negative of green-on-black. In that case the photo negative effect cannot be reached in that environment. (In fact, even in real RGB it probably cannot be fully reached but only approximated, and the approximation would need to know the display's color space and such. But at least subtracting each channel's value from 255 is a good enough approximation for most purposes. Black-on-green is not a good enough approximation of magenta-on-white by any means.)

For black-on-green vs. green-on-black it's fair to say that it's "reverse video", clarifying that it means swapping the bg and fg colors, and _not_ photo negative.

> I can agree that "photo negative" can be ugly on a full colour display (as is common today),
but so is the "swap" interpretation, which I suffer almost every day..., when this is used
for local side text selection marking (no control sequences, not so often seen/used from
the remote side with control sequences).

If you suffer from this almost every day, may I kindly recommend that you fix this problem for yourself? Many terminal emulators allow you to configure the mouse selection color either via the terminal emulator's preferences or via OSC 17 & 19. I have configured my terminal a long time ago to use the same colors as my graphical apps use for mouse highlighting, and I'm very happy with the result. The terminal emulator `terminology` does an even much nicer selection effect out of the box, drawing a border around the selected region and adding diagonal stripes to the area, something you cannot reach via escape sequences. How to show the mouse-highlighted area does not (and should not) belong to ECMA.

Even though terminals often (but not always) apply the same visual effect on mouse highligting as on SGR 7, this doesn't make these two features connected in any way. In one of them you as the user select a piece of text in order to paste it to the clipboard. In the other the developer of the terminal-based application decides to apply "reverse video" for a well-chosen set of character cells, with the intent of implementing a nice usable pleasantly looking monochrome(*) interface. The two are absolutely unrelated. (And coincidentally using the same visual effect does cause some unfortunate real-life issues: https://bugs.launchpad.net/ubuntu/+source/mate-terminal/+bug/1926256.)

(*) Typically SGR 7 is frequently used in apps that implement a monochrome display, such as `top`, `nano` etc., where the app doesn't care about the two main colors the user choses. For apps that shine in full colors, SGR 7 is absolutely unnecessary since the app can just swap the exact color codes that it emits for the foreground (SGR 3x) vs. background (SGR 4x).

For such monochrome apps, swapping the foreground and background colors always results in a nice look, while photo negative often doesn't.

No one actually interprets SGR 7 as photo negative. Everyone interprets it as swapping bg and fg.

Photo negative would look ugly, no one would want to see it, no one is asking for it. Swapping fg and bg looks nice in monochrome apps (`top`, `nano` etc.) and is a widely used feature.

Forcing to switch to photo negative would break the look of those existing apps, with absolutely no way (no workaround) for them to return to the "swap" interpretation (but even if they could, the temporary breakage through the years while apps are catching up would be unacceptable). In turn, photo negative would introduce a feature that no one could use for anything useful.

All the work of decades went against the literal interpretation of ECMA and went for the common sense interpretation. Leave those plethora of working software alone, do not break them. ECMA's wording is broken, fix that.

(Again, as at so many other places, unfortunately what I see is that your proposal is a documentation created based on other pieces of documentation, and has _very_ little connection to the actual real life (i.e. working pieces of software) out there.)

**Comment by kent-karlsson** [comment]
"No. It doesn't matter how many colors are available. Even if black and green are the
only available colors, it does not make black-on-green the photo negative of green-on-black."

OF COURSE IT DOES! That is *exactly* what it does! It is so obvious that it is hard
to give detailed arguments. But in a world where black and green are the only two colours,
of course green is the photo negative of black, and black the photo negative of green.
It cannot be any other way! It is a black-and-green only world!

It does not mean that I think "photo negative" is a great idea. But that is exactly
what is meant, and I do NOT think there was a mistake here in the ECMA-48 5th ed. text.
If you think photo negative is bad, then swapping is much worse (in general; you might
not see any difference in a green-and-black-only world).

And... In the "swap" interpretation, having transparent letters (the most common background
colour in the more general setting of more than two colour planes) on black (the most common
foreground colour) background would not be nice... So the text I have stays, as the "other"
interpretation is both wrong and a bad idea.

None of this seems to be included in any other text styling (HTML/CSS does have "negative"
but for images, not text).
