### ISSUE TITLE
Sane-looking numbers

### ISSUE THREAD

**Issue by egmontkob** [kent-karlsson/control#7]
The use of postfix `=` for negative sign, and `?` for decimal point, make the raw stream terribly ugly and hard to manually create, read, debug.

ECMA-48 5.4 specifies that the format is `CSI P ... P I ... I F`, whereas `-` and `.` belong to the `I` family (intermediates), although we'd need these symbols among the `P` family (parameters) where the digits, `=` and `?` already belong to.

I couldn't find your explanation why you make the negative `=` sign postfix rather than prefix.

---

Anyone who intends to use (be able to parse, interpret, display) your document format could go with a slightly extended (slightly more complicated) grammar. You could change to allow `-` and `.` inside the parameters. Any `-` or `.` that is followed (not necessarily immediately) by a `P`-type character before the final `F` should be re-categorized as a `P`-type rather than `I`-type. In other words, the intermediates are the last full run of characters of the `I` family before `F`, and the rest (a mixture of `P` family, `.` and `-`) are the parameters.

This extension would allow to specify numbers as they usually look like, i.e. using a prefix `-` for negative, or a `.` for decimal point; with the only requirement that the decimal point is then followed by at least one digit (e.g. disallow `5.` as a number).

This makes parsing unique, and a parser confirming to your updated proposal would perfectly handle every string that was created according to the old official ECMA standard. Therefore, no software in active development should have any obstacle in the way of updating their parser.

Compatibility is not guaranteed in the other direction: an old parser, conforming to official ECMA, might misparse escape sequences created using the new standard. But you introduce so many new features, new escape sequences that you can't reasonably expect data interchange to occur in this direction. This rare, unlikely parsing failure is a fair price to pay for having to work with sane-looking numbers for centuries ahead of us. It MUST be declared unsupported to feed a rich text string of your specification into an old-ECMA-confirming parser (e.g. terminal) -- as it _is_, for reasons like not properly handling the currently-proposed `=` (postfix negative) and `?` (decimal point) characters anyway.

If you're proposing an update to the standards, please do it in a way that numbers look the way they look normally. Tailor the spec to the common sense expectations, not the other way around.

(For bonus points, study how `.` is currently used as an intermediate, and see if a trailing `.` in a number can perhaps be allowed without mistaking it for an intermediate.)

**Comment by kent-karlsson** [comment]
Perhaps a bit. But each and every control sequence is hard to manually create, read, debug. The additional
hardness is miniscule.

Yes, that is why = and ? are used. I certainly would **not** support at all messing up the 
format CSI P ... P I ... I F.

While for CSI...m there is no problem (since the number after CSI then is always positive),
there are other control sequences where the first parameter could be a negative number.
And an "=" just after the CSI makes the control sequence private use (i.e. implementation defined).
