### ISSUE TITLE
10-bit colors

### ISSUE THREAD

**Issue by egmontkob** [kent-karlsson/control#8]
The way you add support for 10-bit colors is weird to me, for two different reasons.

---

Reason 1.

One might argue that for displaying rich text, 8 bits per color channel is enough. If anyone says so, I fully accept that.

But maybe it's not. Maybe someone needs more. And if they do, I can't argue with that either.

However, as this being a document interchange format, if you wish to extend the range, you should do it properly.

10-bit is the end result that some high-end video cards or monitors might currently scale to, but in a decade or two it might easily be 12 or 14 bits. You can _not_ say that "8 bits aren't enough, but 10 bits will be enough for many decades to go". Implementations (e.g. hardware manufacturers) can go in steps like 8 -> 10 -> 10⅔ -> 12 -> 14 -> 16 over the years. Inter-component public formats, specifications cannot.

There's already existing precedence in graphic libraries, tools, formats (e.g. png), color codes in html etc. where they figured out 8 bits wouldn't be enough, and so they extended to 16 bits per channel. If 8 isn't enough, jumping straight to 16 is the way (and industry standard) to go, not 10.

Sure you can extend your proposed use of decimals, where currently for 10-bits the highest number is 255.75, but if it's eventually extended to 16 bits then the brighest value would be 255.99609375, c'mon, this looks ridiculous.

---

Reason 2.

The mapping is not correct.

As far as I know, the mapping between the 8-bit and 16-bit subpixel brightness representations is always that the 8-bit value is "doubled" (written twice), i.e. multiplied by 257 (0x0101), e.g. `#AB` of the 8-bit space corresponds to `#ABAB`, and not `#AB00`, of the 16-bit space.

This is the way 8-bit components still access the brightest color by saying 255, and not something (255.0) that is not as bright as 255.75 or 255.99609375.

Your proposed numbering scheme adjusts the lower ends (0) of the two scales, but their higher ends don't exactly align up.

---

To fix both problems, you should design a system that jumps to 16 bits per channel straight away, and makes sure to stretch the values so that both ends of the two scales represent the exact same color.

One possibility is to make up a notation like `123+45` for meaning the high byte is 123 and the low byte is 45, and document that the old notation of `123` is an alias to `123+123` and not `123+0`. (`+` might not be the best choice beucase it's not a mathematical addition. Maybe `/`, although it's not a division either. Or `_`, `'`, `>`, or whatever else that sort of makes sense.)

Another possibility could be to pick an "intermediate" byte, or the first number incremented by let's say 100 (i.e. 102 for direct rgb instead of 2) meaning that the values are to be interpreted on the 0..65535 range rather than on 0..255, or I'm not sure if perhaps the "color space id" is the right field for this.

**Comment by kent-karlsson** [comment]
While I'm a bit set back of the prospect of 16 bits for each RGB colour, I think your suggestion is good.
But I would like to get some references regarding others doing the same. Though I find it highly unlikely
that any hardware will ever really use 16 bits for each RGB colour; if nothing else because human eyes
would not be able to benifit from such a high colour resolution.

I'll use "nnn>nnn", since > is permissible as a "P" character, and is not used for anything else.
You can think of > here as a base-256 decimal marker.
